general:
  root_path: /home/anasmefteh/crns/alpha-beta-crown-evaluation/benchmarks/Cifar2020
  csv_name: instances.csv
  results_file: out.txt
  complete_verifier: bab

model:
  name: cifar_conv_small
  path: /home/anasmefteh/crns/alpha-beta-crown-evaluation/benchmarks/models/eran/cifar_conv_small_pgd.pth
  input_shape: [-1, 3, 32, 32]

data:
  start: 0
  end: 20


solver:
  batch_size: 200
  beta-crown:
    iteration: 20

bab:
  timeout: 120
  branching:
    method: kfsb
    candidates: 10
    reduceop: max